<a href="https://colab.research.google.com/github/NourEldin-Osama/Machine-Learning-Training/blob/main/Copy_of_Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Assignment

In [1]:
import numpy as np

1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.<br>


SOL:  https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php


In [2]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.multiply(ones_array, 5)  # or ones_array * 5
print(zeros_array)
print(ones_array)
print(fives_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2.  Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. <br>
SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-25.php

In [3]:
np.random.randint(10, 21, (3, 4))

array([[12, 20, 20, 19],
       [17, 12, 12, 16],
       [16, 13, 19, 11]])

3.  Write a NumPy program to check whether two arrays are equal (element wise) or not.<br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-44.php

In [4]:
arr1 = np.array(range(1, 6))
arr2 = np.array(range(1, 6))
print(np.equal(arr1, arr2))
arr1 = np.array([1, 3, 2, 4, 5])
print(np.equal(arr1, arr2))

[ True  True  True  True  True]
[ True False False  True  True]


4.  Write a NumPy program to swap rows and columns of a given array in reverse order. <br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-58.php

In [5]:
arr = np.random.randint(1, 11, (2, 6))
print(arr)
print(arr[::-1, ::-1])

[[10  3  4 10  9  3]
 [ 8  1  2  8  2  1]]
[[ 1  2  8  2  1  8]
 [ 3  9 10  4  3 10]]


5. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.<br>
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-4.php

In [6]:
x = np.zeros(10, dtype=np.int32)
x[6] = 11
x

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0], dtype=int32)

6. Write a NumPy program to convert a list and tuple into arrays. <br>
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-11.php

In [7]:
array1 = np.array(list(range(1, 9)))  # list(range(1, 9)) = [1, 2, 3, 4, 5, 6, 7, 8]
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
tuple1 = ([8, 4, 6], [1, 2, 3])
array2 = np.array(tuple1)
array2

array([[8, 4, 6],
       [1, 2, 3]])

7.  Write a NumPy program to change the dimension of an array. <br>
Expected Output:<br>
6 rows and 0 columns<br>
(6,)<br>
(3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>
Change array shape to (3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-35.php

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x.shape = (3, 3)  # or x.reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

8. Write a NumPy program to compute the multiplication of two given matrices.<br>
SOL: https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-1.php

In [10]:
x = np.random.randint(0, 10, (3, 3))
y = np.random.randint(0, 10, (3, 3))
print("x =", x)
print()
print("y =", y)
print()
print("x * y =\n", x.dot(y))  # or np.dot(x, y)

x = [[7 0 9]
 [5 9 6]
 [1 1 3]]

y = [[5 8 5]
 [5 0 2]
 [8 0 5]]

x * y =
 [[107  56  80]
 [118  40  73]
 [ 34   8  22]]


9. Write a NumPy program to create a 3x3x3 array with random values. <br>
Expected Output: <br>
[[[ 0.48941799 0.58722213 0.43453926] <br>
[ 0.94497547 0.81081709 0.1510409 ] <br>
[ 0.66657127 0.29494755 0.48047144]] <br>
[[ 0.02287253 0.95232614 0.32264936] <br>
[ 0.67009741 0.25458304 0.16290913] <br>
[ 0.15520198 0.86826529 0.9679322 ]]  <br>
[[ 0.13503103 0.02042211 0.24683897]  <br>
[ 0.97852158 0.22374748 0.10798856]  <br>
[ 0.62032646 0.5893892 0.16958144]]] <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-random-exercise-3.php

In [11]:
np.random.rand(3, 3, 3)

array([[[0.11148191, 0.99119109, 0.63218625],
        [0.99087253, 0.89044945, 0.12931857],
        [0.41950468, 0.9649162 , 0.70935227]],

       [[0.50537145, 0.91265051, 0.26724842],
        [0.61586537, 0.76904899, 0.09805525],
        [0.95575831, 0.8604493 , 0.34176048]],

       [[0.04060763, 0.85377759, 0.757921  ],
        [0.65122285, 0.65792419, 0.15102041],
        [0.11067379, 0.26561665, 0.77454827]]])

10. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data. <br>
Expected Output: <br>
Sorted indices: <br>
[4 0 5 3 6 1 2] <br>
Sorted data:  <br>
1682 38.0  <br>
1023 40.0  <br>
5241 40.0  <br>
1671 41.0  <br>
4532 42.0  <br>
5202 42.0  <br>
6230 45.0  <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-4.php

In [12]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
# Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:")
for i in indices:
    print(student_id[i], student_height[i])

Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0
